### ISSUE TITLE
Plugin not working unless onPageNotFound event is subscribed with non-zero priority

### ISSUE THREAD

**Issue by a1studmuffin** [hugoaf/grav-plugin-logerrors#1]
Hi there, I just installed this plugin with Grav 1.0.10. By default it doesn't seem to work, though if I edit logerrors.php and change the onPageNotFound event subscribe priority from 0 to 1, it starts working. Thought you'd like to know - happy to provide more information if required. Thanks for the great work on the plugin!

**Comment by haviladev** [comment]
@a1studmuffin  Yeah, I noticed the issue last time we used the plugin, and we applied the same solution you did.
I'll do some additional tests and apply patch accordingly.
Thanks Michael.

**Comment by haviladev** [comment]
Fixed in 1.0.1, thanks.
