### ISSUE TITLE
ADD ip in log file

### ISSUE THREAD

**Issue by Erreur32** [hugoaf/grav-plugin-logerrors#4]
not really an issue ;)

It would be great if you can include IP Visitors in the log file.

**Comment by haviladev** [comment]
I really can't see how the request source IP address is useful for 404 error statistics. @Erreur32, Could you please describe some use cases.

**Comment by Erreur32** [comment]
Thanks for the reply , and thank you for your plugin  ;)   
But  i _have already modified on my side to have it._ ( really dirty way )

It's just to have some statsistic from IP Visitor + URL

To know  which IP  and how many times  ( to exclude some bad BOTs and USERs  with my own script).

I love Grav but  security  it's a pain to check, i mean with FAIL2ban it's not possible to parse the log file correctly.
